import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Layout } from "lucide-react";
import LayoutClient from "@/components/LayoutClient";

const inter = Inter({
  subsets: ["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Laisher - Arquitetura e Engenharia",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-white ${inter.className}`} suppressHydrationWarning
      >
       <LayoutClient>
        {children}
        </LayoutClient>
      </body>
    </html>
  );
}
